apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-12345"
  confluencePageId: "2293761"
  confluenceSpaceId: TS2
  confluencePageTitle: "TechnologyInformationforCMSC"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
  projectInfo:
    name: Test-12345
    moduleName: EAD
    informationAuthor: Selva
    modality: PET
    bodyParts: Brain
    processingPurpose: Task
    protocol: Backstage
    algorithmType: RestAPI
    packageType: Html
    supportedOs: All
    sourceCodeLanguage: TypeScript
    developmentStatus: POC
    linkToProjectPage: Noneas of now

